// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import { useState } from "react";

const theme = {
  bg: "#0D0D0D",
  card: "#161616",
  border: "#282828",
  accent: "#FF5722",
  accentLight: "#FF7A45",
  accentSoft: "rgba(255,87,34,0.08)",
  fg: "#F2F2F2",
  muted: "#999999",
  green: "#42BE65",
  red: "#FA4D56",
  yellow: "#F1C21B",
  kill: "#FA4D56",
};

const price = 169.60;
const prevClose = 169.13;
const change = price - prevClose;
const changePct = prevClose !== 0 ? ((price - prevClose) / prevClose) * 100 : 0;
const timestamp = "2026-06-03 14:55 ET";
const dataTs = "2026-06-03";

function fmt(n: number) { return n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }
function fmtB(n: number) { if (n >= 1e12) return `$${(n / 1e12).toFixed(1)}T`; if (n >= 1e9) return `$${(n / 1e9).toFixed(1)}B`; if (n >= 1e6) return `$${(n / 1e6).toFixed(1)}M`; return fmt(n); }

const tickerItems: [string, string][] = [
  ["Market Cap", fmtB(32649533440)],
  ["Revenue TTM", fmtB(2473555968)],
  ["Rev Growth", "69%"],
  ["Gross Margin", "91.4%"],
  ["Op Margin", "27.6%"],
  ["Net Income", fmtB(707544000)],
  ["FCF", fmtB(564094656)],
  ["Trail P/E", "48.5x"],
  ["Fwd P/E", "19.2x"],
  ["DAUq", "121.4M"],
  ["Cash", fmtB(2770631936)],
  ["Debt", fmtB(21288000)],
];

const redFlags: { label: string; body: string }[] = [
  { label: "Premium multiple with no margin of safety", body: "At 19x forward earnings and 12.7x trailing EV/Revenue, the current price implies 3-4 years of flawless execution. Base case fair value of $197 gives just 16% upside -- well below the 30% minimum for new positions under a GREEN regime." },
  { label: "Advertising revenue concentration risk", body: "Reddit's revenue model is overwhelmingly advertising-driven. Even with AI data licensing deals growing, a digital ad slowdown -- particularly from peak 69% growth -- would compress multiples sharply. Reddit is not immune to the ad cycle." },
  { label: "Google dependency for traffic growth", body: "A material portion of Reddit's new user acquisition and content discovery comes through Google search. An algorithm change or AI-generated search summaries reducing click-through to Reddit would directly hit DAU growth, the platform's most watched metric." },
  { label: "Stock-based compensation still elevated", body: "Despite the $1B buyback authorization, SBC as a percentage of revenue remains meaningful for a company just reaching profitability. Share count continues to creep higher, partially offsetting the buyback's beneficial effect on per-share metrics." },
  { label: "Price well below 52-week high signals market skepticism", body: "Down 40% from the $282.95 high, the market is already pricing in deceleration. The question is whether $170 adequately prices that risk -- at under 30% margin of safety, we don't think so." },
];

const valuationScenarios: { label: string; price: string; updown: string; desc: string; color: string }[] = [
  { label: "Bear", price: "$124", updown: "-27%", desc: "Revenue growth slows to 20%, ad pricing softens, Google dependency becomes a headwind. 22% net margin, 25x multiple on $4.96 EPS.", color: theme.red },
  { label: "Base", price: "$197", updown: "+16%", desc: "Revenue growth moderates to 35%, AI licensing adds incremental revenue, advertising platform matures. 27% net margin, 28x multiple on $7.04 EPS.", color: theme.yellow },
  { label: "Bull", price: "$272", updown: "+60%", desc: "DAU grows past 200M, ARPU converges toward Meta/Google levels, AI data becomes core revenue stream. 30% net margin, 30x multiple on $9.08 EPS.", color: theme.green },
];

const revisitTriggers: string[] = [
  "Price falls below $145 -- providing 30%+ upside to base case fair value of $197. This is the primary trigger.",
  "DAU growth remains above 15% YoY for two consecutive quarters -- confirming the growth trajectory is durable, not a pandemic-era pull-forward.",
  "Operating margins expand above 30% for two consecutive quarters -- proving the ad platform has operating leverage beyond the current ramp.",
  "AI data licensing revenue exceeds 15% of total revenue -- demonstrating diversification away from pure advertising.",
  "SBC as a percentage of revenue falls below 8% -- showing management discipline on dilution alongside the buyback program.",
];

const verdictSummary =
  "Business quality: exceptional. Price: not yet. Reddit has a genuine network effect, 69% revenue growth, 91% gross margins, and a $1B buyback authorization. But at $170, the market is pricing in near-perfect execution. We need $145 or lower before the risk/reward justifies adding to the Value bucket under GREEN regime.";

const sourcesEDGAR =
  "10-K (filed 2026-02-06, Accession 0001713445-26-000001), 10-K (filed 2025-02-13, Accession 0001713445-25-000011), 10-Q (filed 2026-05-01), 8-K (filed 2026-04-22), DEF 14A (filed 2026-04-10), Form 4 (multiple)";

const citationsShort =
  "RDDT 10-K filed 2026-02-06: business, mdna, risk_factors sections. 10-K filed 2025-02-13: business, mdna, risk_factors. SEC EDGAR via Clarion Intelligence System secrag pipeline. Live price and fundamentals via yfinance (point-in-time, 2026-06-03).";

const passParagraphs = [
  "Reddit is, by most measures, exactly the kind of business we want to own. It has a genuine network effect -- 121.4 million daily active users across 100,000+ communities, growing 19% year-over-year. Revenue is growing 69% to $2.47 billion, gross margins are 91.4%, and the company just became meaningfully profitable with $707 million in net income and $564 million in free cash flow.",
  "The moat is real. Reddit's communities are organized around topics, not social graphs -- which means the platform gets stickier as it grows, not more brittle. The content corpus -- nearly two decades of human conversation across every imaginable subject -- is a data asset that AI companies like Google and OpenAI are now paying to access.",
  "Management is showing capital allocation discipline. After years of investor concern about dilution, the Board authorized a $1 billion share repurchase program in February 2026. The balance sheet is pristine: $2.77 billion in cash against just $21 million in debt. The forward P/E of 19.2x is reasonable for a company growing at this rate.",
  "So why are we waiting? Because we are value investors, not momentum investors. At $170, the base case fair value of $197 offers just 16% upside from here. Under GREEN regime, our hurdle rate is 8.5%, and we require a 30% margin of safety on new positions. The bear case at $124 (-27%) is not remote -- it requires only that revenue growth moderate to 20% in an advertising downturn. Three months ago this stock was at $283. The market's enthusiasm has cooled, but the price hasn't yet cooled enough for our discipline.",
  "The math is straightforward. If we're wrong and the bull case plays out -- ARPU converges toward Meta levels, DAU doubles, AI licensing becomes a third revenue pillar -- we miss a 60% gain. But if we're right about the margin of safety requirement, we either buy this cheaper or we deploy the capital into a name where the upside is clearer. Equity vs. T-bills is the frame: at the current price, the expected return doesn't clear the hurdle with enough margin to sleep well.",
];

export default function RDDTPage() {
  const tabStyle = (key: string) => ({
    background: "none",
    border: "none",
    color: tab === key ? theme.fg : theme.muted,
    borderBottom: tab === key ? `2px solid ${theme.accent}` : "2px solid transparent",
    padding: "12px 14px",
    fontSize: 13,
    cursor: "pointer",
    fontWeight: tab === key ? 600 : 400,
  });
  return (
    <div style={{ minHeight: "100vh" }}>
      <style>{`[data-zo-built-on-badge="true"]{display:none !important;}`}</style>
      {/* NAV */}
      <div style={{ borderBottom: `1px solid ${theme.border}`, padding: "12px 24px", display: "flex", justifyContent: "space-between", alignItems: "center", background: "rgba(0,0,0,0.6)" }}>
        <a href="https://cis.zo.space" style={{ fontSize: 12, color: theme.muted, letterSpacing: "0.08em", textTransform: "uppercase", textDecoration: "none" }}>Clarion Intelligence Systems</a>
        <span style={{ fontSize: 11, color: theme.muted }}>GREEN · SPY +5.8% · TLT +0.7% · 2026-06-03</span>
      </div>

      <div style={{ maxWidth: 900, margin: "0 auto", padding: "32px 20px" }}>

        {/* HEADER */}
        <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", flexWrap: "wrap", gap: 20, marginBottom: 28 }}>
          <div>
            <div style={{ display: "flex", alignItems: "center", gap: 14, marginBottom: 8 }}>
              <div style={{ width: 48, height: 48, borderRadius: 8, background: theme.accent, display: "flex", alignItems: "center", justifyContent: "center" }}>
                <span style={{ fontSize: 18, fontWeight: 800, color: theme.bg }}>RD</span>
              </div>
              <div>
                <div style={{ fontSize: 28, fontWeight: 700, letterSpacing: "0.02em" }}>RDDT</div>
                <div style={{ fontSize: 13, color: theme.muted }}>Reddit, Inc.</div>
              </div>
            </div>
            <div style={{ fontSize: 12, color: theme.yellow, background: "rgba(241,194,27,0.10)", border: "1px solid rgba(241,194,27,0.25)", borderRadius: 6, padding: "4px 10px", display: "inline-block" }}>
              Watchlist -- {dataTs}
            </div>
          </div>
          <div style={{ textAlign: "right" }}>
            <div style={{ fontSize: 42, fontWeight: 700, letterSpacing: "-0.03em" }}>${fmt(price)}</div>
            <div style={{ fontSize: 16, color: change >= 0 ? theme.green : theme.red, fontWeight: 600 }}>
              {change >= 0 ? "\u25B2" : "\u25BC"} ${Math.abs(change).toFixed(2)} ({Math.abs(changePct).toFixed(2)}%)
            </div>
            <div style={{ fontSize: 11, color: theme.muted, marginTop: 4 }}>Close {timestamp} -- via yfinance -- {dataTs}</div>
          </div>
        </div>

        {/* WATCHLIST VERDICT */}
        <div style={{ background: "linear-gradient(135deg, rgba(241,194,27,0.10), rgba(241,194,27,0.03))", border: `1px solid ${theme.border}`, borderRadius: 12, padding: "18px 22px", marginBottom: 24 }}>
          <div style={{ fontSize: 11, color: theme.yellow, textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 6 }}>Verdict</div>
          <div style={{ fontSize: 17, fontWeight: 600, lineHeight: 1.4 }}>{verdictSummary}</div>
        </div>

        {/* STATS BAR */}
        <div style={{ display: "grid", gridTemplateColumns: "repeat(6, 1fr)", gap: 10, marginBottom: 24 }}>
          {tickerItems.slice(0, 12).map(([label, value]) => (
            <div key={label} style={{ background: theme.card, border: `1px solid ${theme.border}`, borderRadius: 10, padding: "12px 10px", textAlign: "center" }}>
              <div style={{ fontSize: 16, fontWeight: 700, color: value.startsWith("-") ? theme.red : theme.accent }}>{value}</div>
              <div style={{ fontSize: 10, color: theme.muted, marginTop: 3, textTransform: "uppercase", letterSpacing: "0.06em" }}>{label}</div>
            </div>
          ))}
        </div>

        {/* TABS */}
        <div style={{ display: "flex", gap: 4, marginBottom: 20, borderBottom: `1px solid ${theme.border}` }}>
          {tabs.map(([key, label]) => (
            <button key={key} onClick={() => setTab(key)} style={tabStyle(key)}>
              {label}
            </button>
          ))}
        </div>

        {/* TAB: Why I'm Waiting */}
        {tab === "pass" && (
          <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
            <div style={{ background: theme.card, border: `1px solid ${theme.border}`, borderRadius: 12, padding: 22 }}>
              <h2 style={{ fontSize: 22, fontWeight: 700, color: theme.fg, margin: "0 0 20px 0" }}>Why I'm Waiting</h2>
              {passParagraphs.map((p, i) => (
                <p key={i} style={{ fontSize: 14, color: theme.muted, lineHeight: 1.7, marginBottom: 12 }}>{p}</p>
              ))}
            </div>
            <div style={{ background: "rgba(250,77,86,0.06)", border: "1px solid rgba(250,77,86,0.2)", borderRadius: 12, padding: 22 }}>
              <div style={{ fontSize: 12, color: theme.kill, textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 14 }}>Risk Factors</div>
              {redFlags.map((rf, i) => (
                <div key={i} style={{ display: "flex", alignItems: "flex-start", gap: 12, marginBottom: 12, padding: "12px 14px", background: "rgba(250,77,86,0.06)", borderRadius: 8, border: "1px solid rgba(250,77,86,0.12)" }}>
                  <span style={{ fontSize: 20, fontWeight: 800, color: i === 0 ? theme.red : theme.yellow }}>{i + 1}</span>
                  <div>
                    <div style={{ fontSize: 13, color: theme.fg, fontWeight: 600, marginBottom: 4 }}>{rf.label}</div>
                    <div style={{ fontSize: 12, color: theme.muted, lineHeight: 1.6 }}>{rf.body}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* TAB: SEC Evidence */}
        {tab === "evidence" && (
          <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
            <div style={{ background: theme.card, border: `1px solid ${theme.border}`, borderRadius: 12, padding: 18, marginBottom: 4 }}>
              <div style={{ fontSize: 11, color: theme.muted, marginBottom: 4 }}>SEC Filing Indexed</div>
              <div style={{ fontSize: 14, fontWeight: 600 }}>10-K Annual Report (filed 2026-02-06)</div>
              <div style={{ fontSize: 12, color: theme.muted, marginTop: 2 }}>{sourcesEDGAR}</div>
            </div>

            {/* Evidence Items */}
            <div style={{ background: theme.card, border: `1px solid ${theme.border}`, borderRadius: 10, padding: 18 }}>
              <div style={{ fontSize: 12, color: theme.accent, textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 10 }}>Moat Evidence</div>
              <div style={{ fontSize: 13, color: theme.fg, lineHeight: 1.6, marginBottom: 10 }}>Reddit's 10-K describes 121.4 million DAUq ("daily active unique") across 100,000+ active communities, growing 19% YoY. Communities are organized by topic, not social connection -- a structural moat that deepens with scale. The content corpus spans nearly 20 years of indexed conversation.</div>
              <div style={{ fontSize: 11, color: theme.muted }}>RDDT 10-K filed 2026-02-06, business section</div>
            </div>

            <div style={{ background: theme.card, border: `1px solid ${theme.border}`, borderRadius: 10, padding: 18 }}>
              <div style={{ fontSize: 12, color: theme.accent, textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 10 }}>Management & Capital Allocation</div>
              <div style={{ fontSize: 13, color: theme.fg, lineHeight: 1.6, marginBottom: 10 }}>On February 4, 2026, the Board authorized a $1 billion share repurchase program. This is a meaningful shift in capital allocation for a company that has historically been dilutive through SBC. The buyback signals management confidence in free cash flow durability. The balance sheet carries $2.77B cash against $21M debt -- essentially unlevered.</div>
              <div style={{ fontSize: 11, color: theme.muted }}>RDDT 10-K filed 2026-02-06, mdna section; 8-K filed 2026-02-06</div>
            </div>

            <div style={{ background: theme.card, border: `1px solid ${theme.border}`, borderRadius: 10, padding: 18 }}>
              <div style={{ fontSize: 12, color: theme.accent, textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 10 }}>Financial Trends</div>
              <div style={{ fontSize: 13, color: theme.fg, lineHeight: 1.6, marginBottom: 10 }}>Revenue grew 69% to $2.47B TTM, driven by advertising platform scaling and AI data licensing deals. Gross margins remain exceptional at 91.4%. The company began generating net positive operating cash flows in 2024 and has since expanded to $564M in FCF. Operating margin reached 27.6%, demonstrating significant operating leverage.</div>
              <div style={{ fontSize: 11, color: theme.muted }}>RDDT 10-K filed 2026-02-06, mdna section; fundamentals via yfinance</div>
            </div>

            <div style={{ background: theme.card, border: `1px solid ${theme.border}`, borderRadius: 10, padding: 18 }}>
              <div style={{ fontSize: 12, color: theme.accent, textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 10 }}>Risk Factors</div>
              <div style={{ fontSize: 13, color: theme.fg, lineHeight: 1.6, marginBottom: 10 }}>Reddit's 10-K identifies material risks including: dependency on Google search for traffic acquisition, advertising revenue concentration, competition from larger platforms (Meta, Google, TikTok) for digital ad budgets, regulatory risk around content moderation and Section 230, and the challenge of monetizing international users at comparable ARPU levels to US users.</div>
              <div style={{ fontSize: 11, color: theme.muted }}>RDDT 10-K filed 2026-02-06, risk_factors section</div>
            </div>
          </div>
        )}

        {/* TAB: Valuation */}
        {tab === "valuation" && (
          <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
            <div style={{ background: theme.card, border: `1px solid ${theme.border}`, borderRadius: 12, padding: 22 }}>
              <div style={{ fontSize: 12, color: theme.accent, textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 18 }}>Valuation Scenarios</div>
              <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 12 }}>
                {valuationScenarios.map((s) => (
                  <div key={s.label} style={{ background: s.color + "0D", border: `1px solid ${s.color}33`, borderRadius: 10, padding: 16 }}>
                    <div style={{ fontSize: 11, color: s.color, fontWeight: 700, textTransform: "uppercase", marginBottom: 8 }}>{s.label}</div>
                    <div style={{ fontSize: 28, fontWeight: 700, color: theme.fg, marginBottom: 4 }}>{s.price}</div>
                    <div style={{ fontSize: 13, color: s.color, fontWeight: 600, marginBottom: 10 }}>{s.updown}</div>
                    <div style={{ fontSize: 12, color: theme.muted, lineHeight: 1.5 }}>{s.desc}</div>
                  </div>
                ))}
              </div>
              <div style={{ marginTop: 20, padding: "14px 16px", background: "rgba(241,194,27,0.06)", border: "1px solid rgba(241,194,27,0.18)", borderRadius: 8 }}>
                <div style={{ fontSize: 12, color: theme.yellow, fontWeight: 600, marginBottom: 6 }}>Price That Would Change My Mind</div>
                <div style={{ fontSize: 13, color: theme.fg, lineHeight: 1.5 }}>
                  At $145 or below, the base-case upside exceeds 35% and the risk/reward clears the GREEN regime hurdle with adequate margin of safety. At that level, expected return vs. T-bills becomes compelling.
                </div>
              </div>
            </div>
          </div>
        )}

        {/* TAB: Revisit Triggers */}
        {tab === "revisit" && (
          <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
            <div style={{ background: theme.card, border: `1px solid ${theme.border}`, borderRadius: 12, padding: 22 }}>
              <h2 style={{ fontSize: 22, fontWeight: 700, color: theme.fg, margin: "0 0 20px 0" }}>Revisit Triggers</h2>
              <p style={{ fontSize: 13, color: theme.muted, margin: "0 0 16px 0", lineHeight: 1.6 }}>
                If any of these conditions are met, RDDT should be re-evaluated for an Add. The first trigger is the primary one -- it's a price discipline rule. The remaining triggers are business quality checks that would justify a higher fair value estimate.
              </p>
              {revisitTriggers.map((t, i) => (
                <div key={i} style={{ display: "flex", gap: 12, marginBottom: 10, padding: "12px 14px", background: "rgba(66,190,101,0.06)", borderRadius: 8, border: "1px solid rgba(66,190,101,0.15)" }}>
                  <span style={{ fontSize: 14, fontWeight: 700, color: theme.green, flexShrink: 0 }}>{i + 1}.</span>
                  <span style={{ fontSize: 13, color: theme.fg, lineHeight: 1.5 }}>{t}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* SOURCES */}
        <div style={{ marginTop: 32, padding: "16px 20px", background: theme.card, border: `1px solid ${theme.border}`, borderRadius: 10 }}>
          <div style={{ fontSize: 11, color: theme.muted, textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 6 }}>Sources</div>
          <div style={{ fontSize: 11, color: theme.muted, lineHeight: 1.6 }}>{citationsShort}</div>
        </div>

        {/* FOOTER */}
        <div style={{ marginTop: 32, padding: "14px 0", borderTop: `1px solid ${theme.border}`, display: "flex", justifyContent: "space-between", fontSize: 11, color: theme.muted }}>
          <span>Clarion Intelligence Systems LLC -- Research only, not investment advice</span>
          <span>Price: yfinance -- SEC: EDGAR (0001713445-26-000001) -- {dataTs}</span>
        </div>
      </div>
    </div>
  );
}