// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import { useState, useEffect } from "react";

const theme = {
  bg: "#1A1B1E",
  card: "#232427",
  border: "rgba(84, 81, 75, 0.45)",
  accent: "#F7F7F4",
  accentLight: "#F7F7F4",
  accentSoft: "rgba(247,247,244,0.08)",
  fg: "#F7F7F4",
  muted: "#9A958C",
  green: "#42BE65",
  red: "#FA4D56",
  yellow: "#9A958C",
  kill: "#FA4D56",
  serif: "'Newsreader', 'Tiempos Headline', Georgia, serif",
  sans: "'Inter', 'Suisse Intl', system-ui, sans-serif",
};

const price = 88.56;
const prevClose = 91.57;
const change = price - prevClose;
const changePct = prevClose !== null ? ((price - prevClose) / prevClose) * 100 : 0;
const priceAsOf = "2026-08-20 15:45 UTC";
function fmt(n: number) { return n.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2}); }
function fmtB(n: number) { if(n>=1e12) return `$${(n/1e12).toFixed(1)}T`; if(n>=1e9) return `$${(n/1e9).toFixed(1)}B`; if(n>=1e6) return `$${(n/1e6).toFixed(1)}M`; return fmt(n); }

const tickerItems: [string,string][] = [
  ["Price","$88.56"],
  ["Verdict","HOLD"],
  ["Health","69/100"],
  ["Fwd P/E (FY27E)","12.0×"],
  ["Ex-Cash P/E","10.9×"],
  ["Mkt Cap",fmtB(12.13e9)],
  ["ROE","42.6%"],
  ["HOKA/UGG TTM","95.9%"],
  ["Net Mgn","18.4%"],
  ["D/E","21%"],
  ["FCF Yield","7.2%"],
  ["Rev Grth (Q1)","+5.7%"],
];

const metrics: [string,string][] = [
  ["Trail P/E","12.7×"],["Fwd P/E","12.0×"],["Mkt Cap",fmtB(12.13e9)],["ROE","42.6%"],["Op Mgn","23.1%"],["Net Mgn","18.4%"],
  ["D/E","21%"],["Gr Mgn (Q1)","56.4%"],["Rev Grth","+5.7%"],["FCF",fmtB(871e6)],["Net Cash",fmtB(1.13e9)],["EPS (FY26)","$7.02"],
];

const evidence: [string,string,string,string][] = [
  ["1","Moat","Q1 FY27 8-K","Gross margin rose to 56.4% from 55.8% year over year, and management raised the FY2027 gross margin outlook to \"slightly better than 56.5%\". Pricing power is intact — DECK is still selling into brand equity, not discounting."],
  ["2","Moat","FY26 10-K / 8-K","HOKA reached $2.587B in FY2026 (+15.9%) against UGG at $2.739B (+8.2%). HOKA is now 47% of revenue and closing on UGG; the crossover — when a year-round performance brand becomes the largest line — is the structural re-rating event, tracking FY2027-28."],
  ["3","Management","Q1 FY27 8-K","Stefano Caroti has served as President and CEO since August 2024. Capital allocation is the clearest signal: $338.2M repurchased in Q1 FY27 alone, with roughly $4.7B of authorization remaining — equal to 39% of the current market capitalization."],
  ["4","Financials","Q1 FY27 10-Q","Cash $1.603B against total debt $472M — $1.13B net cash, or $8.30 per share, with no outstanding borrowings. Inventories fell to $807.6M from $849.4M. FCF $871M TTM on a $12.1B market cap is a 7.2% yield."],
  ["5","Risk","Q1 FY27 8-K / 10-Q","HOKA growth decelerated to +7.7% from +15.9% in FY2026. Management attributes the international wholesale shortfall to \"planned shipment timing differences primarily from the transition of our European 3PL in the prior period\" — a base effect. Constant-currency company growth was 4.8% versus 5.7% reported, and total units sold fell 1.4%, so growth is price and mix rather than volume."],
  ["6","Risk","Q1 FY27 10-Q, Note 10","Segment income from operations was $316.0M versus $315.3M — flat. The 6.0% decline in consolidated operating income to $155.3M came from unallocated corporate expense rising $10.7M, attributed primarily to foreign-currency remeasurement losses and IT spend. Real degradation is at the segment margin line: 31.0% versus 32.7%, with HOKA at 36.3% versus 38.8% as store count went to 68 from 48."],
  ["7","Catalyst","Q1 FY27 10-Q","The Supreme Court invalidated IEEPA tariffs in February 2026 and the Court of International Trade ordered refunds in March. DECK paid roughly $120M gross and began filing claims under CAPE Phase 2 after June 30, 2026. Explicitly excluded from guidance — unbudgeted upside."],
  ["8","Insider","Form 4, Aug 15-19 2026","Fifteen Form 4s in two days are all annual equity grants (code A) and tax withholding on vesting (code F) — zero open-market sales. CEO Caroti holds 460,949 shares post-grant; CFO Fasching 140,844. Still no open-market insider buying."],
  ["9","Catalyst","FY26 10-K + Q1 FY27 10-Q, Note 10","The crossover, measured directly: TTM HOKA net sales as a percentage of TTM UGG net sales ran 88.2% (Mar-2025), 92.5% (Dec-2025), 94.5% (Mar-2026), 95.9% (Jun-2026). HOKA gained 139bps on UGG in the same quarter its growth rate halved, because UGG decelerated to +4.9%. This is now kill condition 1."],
];

const killConditions: [string,string,string][] = [
  ["1","HOKA share of the book stops advancing — TTM HOKA net sales as a % of TTM UGG net sales fails to increase for 2 consecutive quarters — CLEAR (revised 2026-08-20)","Ratio: 88.2% (Mar-25) → 92.5% (Dec-25) → 94.5% (Mar-26) → 95.9% (Jun-26). Still rising, and it rose 139bps in the quarter HOKA \"decelerated.\" Replaces a raw 10% growth-rate trigger, which conflated demand impairment with FX, channel mix, and base effects."],
  ["1b","HOKA demand impairment — HOKA net sales DECLINE YoY in 2 consecutive quarters, OR HOKA segment gross margin contracts >150bps YoY for 2 consecutive quarters — CLEAR (added 2026-08-20)","Q1 FY27 HOKA +7.7%, segment gross margin 57.2% vs 57.7% (−50bps). This is the real exit test: shrinking, or buying growth with discounts. Neither is happening."],
  ["2","Consolidated gross margin contracts >200bps YoY for 2 consecutive quarters — clear","Q1 FY27 +60bps, prior quarter +90bps. Still expanding; not close."],
  ["3","Large dilutive M&A of a non-core brand — clear","No acquisitions. Capital returned via buyback."],
  ["4","Tariff-driven COGS increase >500bps that management cannot offset — clear","Reversed into a tailwind; ~$120M IEEPA refund claim filed."],
  ["5","UGG net sales decline YoY for 2 consecutive quarters — clear","Q1 FY27 UGG +4.9%, prior quarter +9.2%. Decelerating but positive."],
  ["6","SEGMENT operating margin (HOKA + UGG + Other) contracts YoY for 4 consecutive quarters — ARMED, 2 of 4 (added 2026-08-20, restated to segment basis)","Q4 FY26 31.4% vs 33.8% (−246bps); Q1 FY27 31.0% vs 32.7% (−170bps). Measured at the segment line because consolidated operating margin absorbs corporate FX remeasurement noise, which is not a business signal."],
];

const quotes: [string,string][] = [
  ["The business got worse and the price got worse faster. HOKA halving its growth rate is a genuine impairment, not noise. But the stock fell 13.5% after a print in which management raised full-year EPS guidance.","— Q1 FY2027 thesis review (2026-08-20)"],
];

export default function DeckPage() {
  const [tab, setTab] = useState("corethesis");
  const tabs = ["Core Thesis","SEC Evidence","Valuation","Position Mgmt","Screener"];
  const [thesisMeta, setThesisMeta] = useState<any>(null);
  useEffect(() => {
    fetch("/api/thesis/DECK", {headers:{Accept:"application/json"}})
      .then(r => r.json())
      .then(d => d.ticker ? setThesisMeta(d) : null)
      .catch(() => {});
  }, []);
  const pos = thesisMeta || {};
  return (
    <div className="thesis-root" style={{minHeight:"100vh",background:theme.bg,color:theme.fg,fontFamily:theme.sans}}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,500;6..72,600;6..72,700&family=Inter:wght@400;500;600;700&display=swap');
.thesis-root * { border-radius: 0 !important; }
[data-zo-built-on-badge] { display: none !important; }`}</style>
      <div style={{maxWidth:1000,margin:"0 auto",padding:"36px 24px 60px"}}>
        {/* Header */}
        <div style={{fontSize:11,color:theme.muted,marginBottom:12,letterSpacing:0.5}}>
          <a href="https://elendillabs.com" style={{color:"inherit",textDecoration:"none"}}>Elendil Labs</a>
        </div>
        <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:28,flexWrap:"wrap",gap:16}}>
          <div>
            <div style={{fontSize:11,color:theme.muted,textTransform:"uppercase",letterSpacing:1,marginBottom:4}}>DECK</div>
            <h1 style={{fontSize:28,fontWeight:700,margin:"0 0 4px",fontFamily:theme.serif}}>Deckers Outdoor Corp.</h1>
            <div style={{fontSize:13,color:theme.accent,fontWeight:600,marginBottom:4}}>HOLD · Health 69/100 · Reviewed Aug 20, 2026</div>
            <div style={{fontSize:12,color:theme.muted}}>NYSE · Consumer Discretionary · HOKA &amp; UGG Brands</div>
          </div>
          <div style={{textAlign:"right"}}>
            <div style={{fontSize:36,fontWeight:800,color:theme.fg}}>${fmt(price)}</div>
            <div style={{fontSize:14,color:change>=0?theme.green:theme.red}}>{change>=0?"+":""}{fmt(change)} ({changePct>=0?"+":""}{fmt(changePct)}%)</div>
            <div style={{fontSize:11,color:theme.muted,marginTop:2}}>Aug 20, 2026</div>
            {(() => {
  const asOf = new Date(priceAsOf);
  const days = Math.floor((Date.now() - asOf.getTime()) / 86400000);
  if (days > 2) return (<div style={{fontSize:10,color:"#FA4D56",background:"rgba(250,77,86,0.1)",border:"1px solid rgba(250,77,86,0.25)",borderRadius:4,padding:"2px 8px",marginTop:6,display:"inline-block"}}>Stale - research-grade only ({days}d old)</div>);
  return null;
})()}
          </div>
        </div>
        {/* Ticker summary grid */}
        <div style={{display:"grid",gridTemplateColumns:"repeat(6,1fr)",gap:10,marginBottom:28}}>
          {tickerItems.map(([label,value]) => (
            <div key={label} style={{background:theme.card,border:`1px solid ${theme.border}`,borderRadius:10,padding:"12px 10px",textAlign:"center"}}>
              <div style={{fontSize:11,color:theme.muted,textTransform:"uppercase",letterSpacing:0.5,marginBottom:4}}>{label}</div>
              <div style={{fontSize:14,fontWeight:700,color:value==="ADD"||value==="ACTIVE"?theme.green:theme.fg}}>{value}</div>
            </div>
          ))}
        </div>
        {/* Tabs */}
        <div style={{display:"flex",gap:4,marginBottom:28,flexWrap:"wrap"}}>
          {tabs.map((t) => (
            <button key={t} onClick={() => setTab(t.toLowerCase().replace(/ /g,""))}
              style={{padding:"10px 22px",borderRadius:8,border:`1px solid ${tab===t.toLowerCase().replace(/ /g,"")?theme.accent:theme.border}`,background:tab===t.toLowerCase().replace(/ /g,"")?theme.accentSoft:"transparent",color:tab===t.toLowerCase().replace(/ /g,"")?theme.accent:theme.muted,fontSize:13,fontWeight:600,cursor:"pointer"}}>{t}</button>
          ))}
        </div>
        {/* Tab content */}
        {tab==="corethesis" && (
          <div style={{background:theme.card,border:`1px solid ${theme.border}`,borderRadius:14,padding:28}}>
            <h2 style={{fontSize:22,fontWeight:700,margin:"0 0 16px",color:theme.accent}}>What I Believe</h2>
            <div style={{background:"rgba(250,77,86,0.08)",border:"1px solid rgba(250,77,86,0.25)",borderRadius:10,padding:"12px 16px",marginBottom:18}}>
              <div style={{fontSize:12,fontWeight:700,color:theme.kill,marginBottom:4}}>REVISED 2026-08-20 AFTER Q1 FY2027 · KILL CONDITION 1 REWRITTEN SAME DAY</div>
              <div style={{fontSize:13,lineHeight:1.6,color:theme.fg}}>The prior version called DECK a "margin-expanding compounder." That framing is half-wrong and has been rewritten rather than defended. Base case cut $164 → $140. Health 72 → 67 on the first pass, then 67 → 69 after segment-level data showed the operating-income decline was corporate FX, not brand economics. Kill condition 1 — a raw "HOKA below 10% growth" trigger — was replaced the same day with a test of the actual thesis. That amendment was made while the old condition was armed; the reasoning is stated in full below and in the thesis file history.</div>
            </div>
            <p style={{fontSize:14,lineHeight:1.75,color:theme.fg,margin:"0 0 14px 0"}}>Deckers owns two of the most recognizable footwear brands in the world — UGG and HOKA — and trades at $88.56, or 11.9× the midpoint of management's own raised FY2027 EPS guidance of $7.35–$7.50. Strip out $1.13B of net cash ($8.30 per share) and the operating business trades at 10.8× — a 9.2% earnings yield on a debt-free business earning 42.6% on equity.</p>
            <p style={{fontSize:14,lineHeight:1.75,color:theme.fg,margin:"0 0 14px 0"}}>What actually changed, stated precisely: <strong>segment</strong> operating income was $316.0M against $315.3M — essentially flat. The 6.0% decline in <em>consolidated</em> operating income came entirely from unallocated corporate expense, which rose $10.7M, and the 10-Q attributes that primarily to higher foreign-currency remeasurement losses plus IT spend. That is not brand economics. What <em>is</em> real: segment operating margin fell to 31.0% from 32.7%, and HOKA's own segment margin fell to 36.3% from 38.8% as the brand added 20 retail stores (68 versus 48) and grew segment payroll 26.8%. Gross margin expanded — 56.4% versus 55.8% — so none of this is discounting.</p>
            <p style={{fontSize:14,lineHeight:1.75,color:theme.fg,margin:"0 0 14px 0"}}>The revised claim: <strong>DECK is a high-single-digit revenue grower reinvesting gross margin into brand and owned distribution, converting that into low-double-digit EPS growth through a buyback authorization equal to 39% of its own market capitalization.</strong> It is not a margin-expansion story. It is a capital-allocation story attached to two brands with intact pricing power. At 12× forward earnings, that is enough.</p>
            <p style={{fontSize:14,lineHeight:1.75,color:theme.fg,margin:"0 0 14px 0"}}>On the deceleration: HOKA grew 7.7%, down from 15.9% in FY2026. Three things qualify the number. Management attributes the international wholesale shortfall to <em>"planned shipment timing differences primarily from the transition of our European 3PL in the prior period"</em> — an inflated base, not lost demand. Company inventory <em>fell</em> to $807.6M from $849.4M, which is not what a demand break looks like. And DTC grew 13.0% against wholesale at 2.2%, a deliberate, margin-accretive channel shift. Cutting the other way: constant-currency growth was 4.8% versus 5.7% reported, total units sold fell 1.4%, and HOKA's segment gross margin slipped 50bps. Growth is coming from price and mix, not volume.</p>
            <p style={{fontSize:14,lineHeight:1.75,color:theme.fg,margin:"0 0 14px 0"}}>Which is why kill condition 1 was rewritten. A 10% growth threshold does not test this thesis — it conflates demand impairment with FX, channel mix, base effects, and the retail cycle. The thesis is that <strong>HOKA overtakes UGG and the market re-rates the company around a year-round performance brand.</strong> The falsifiable version of that is the ratio of TTM HOKA sales to TTM UGG sales: 88.2% → 92.5% → 94.5% → <strong>95.9%</strong>. It advanced 139bps in the very quarter that armed the old condition, because UGG decelerated too. At this pace the crossover lands around the March 2027 quarter, on schedule. If that ratio stalls for two quarters, the reason to own this stock is gone — regardless of what the growth rate prints.</p>
            <p style={{fontSize:14,lineHeight:1.75,color:theme.fg,margin:"0 0 14px 0"}}>The consequence for sizing: the October print is no longer a liquidation binary. It is a sizing decision. That makes the position easier to build, and it is exactly why the amendment deserves the scrutiny flagged at the top of this page rather than quiet acceptance.</p>
            <h3 style={{fontSize:16,fontWeight:700,color:theme.fg,margin:"24px 0 12px"}}>Kill Conditions</h3>
            <div style={{display:"flex",flexDirection:"column",gap:8}}>
              {killConditions.map(([n,cond,monitor]) => (
                <div key={n} style={{background:theme.bg,border:`1px solid ${theme.kill}20`,borderRadius:10,padding:"12px 16px",display:"flex",gap:12,alignItems:"flex-start"}}>
                  <span style={{color:theme.kill,fontWeight:700,fontSize:13,minWidth:24}}>{n}</span>
                  <div>
                    <div style={{fontSize:13,color:theme.fg,fontWeight:600}}>{cond}</div>
                    <div style={{fontSize:11,color:theme.muted,marginTop:2}}>{monitor}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
        {tab==="secevidence" && (
          <div style={{background:theme.card,border:`1px solid ${theme.border}`,borderRadius:14,padding:28}}>
            <h2 style={{fontSize:22,fontWeight:700,margin:"0 0 16px",color:theme.accent}}>SEC Evidence</h2>
            <p style={{fontSize:12,color:theme.muted,margin:"0 0 20px"}}>Q1 FY2027 8-K filed 2026-07-23 (0000910521-26-000015) · 10-Q filed 2026-07-30 (0000910521-26-000022) · Q4/FY26 8-K filed 2026-05-21 (0000910521-26-000007) · Form 4s filed 2026-08-15 to 2026-08-19</p>
            {evidence.map(([n,tag,section,text]) => (
              <div key={n} style={{marginBottom:20,paddingBottom:20,borderBottom:`1px solid ${theme.border}`}}>
                <div style={{display:"flex",gap:8,alignItems:"center",marginBottom:6}}>
                  <span style={{background:theme.accentSoft,color:theme.accent,padding:"2px 8px",borderRadius:4,fontSize:11,fontWeight:600}}>{tag}</span>
                  <span style={{fontSize:11,color:theme.muted}}>{n}. {section}</span>
                </div>
                <p style={{fontSize:14,lineHeight:1.7,color:theme.fg,margin:0}}>{text}</p>
              </div>
            ))}
            {quotes.map(([q,attr],i) => (
              <div key={i} style={{marginTop:20,padding:"16px 20px",background:theme.accentSoft,borderRadius:10,borderLeft:`3px solid ${theme.accent}`}}>
                <p style={{fontSize:13,lineHeight:1.65,fontStyle:"italic",color:theme.fg,margin:"0 0 6px"}}>"{q}"</p>
                <p style={{fontSize:11,color:theme.muted,margin:0}}>{attr}</p>
              </div>
            ))}
          </div>
        )}
        {tab==="valuation" && (
          <div style={{background:theme.card,border:`1px solid ${theme.border}`,borderRadius:14,padding:28}}>
            <h2 style={{fontSize:22,fontWeight:700,margin:"0 0 16px",color:theme.accent}}>Valuation</h2>
            <p style={{fontSize:13,color:theme.muted,margin:"0 0 24px"}}>Earnings power to FY2030 off management's own FY2028-30 framework, discounted against the ORANGE regime hurdle of 9.70%. Revised 2026-08-20.</p>
            <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:16,marginBottom:32}}>
              {[["Bear","Discretionary recession. HOKA growth falls to 0-3%, UGG declines, operating margin compresses to 18%, EPS about $5.75 at 11.5×. Buyback still cushions the share count.","$66","−26%"],["Base","Management's FY2028-30 framework delivers: high-single-digit revenue, operating margin held in the low 20s, low-double-digit EPS growth. FY2030 EPS about $9.88 at a 14.2× exit multiple.","$140","+58%"],["Bull","HOKA reaccelerates to low-teens and operating margin recovers toward 23%. FY2030 EPS about $10.85 at 18×. Tariff refund is upside on top.","$195","+119%"]].map(([s,a,fv,ud],i) => (
                <div key={s} style={{background:theme.bg,border:`1px solid ${s==="Base"?theme.accent:theme.border}`,borderRadius:12,padding:20}}>
                  <div style={{fontSize:12,color:s==="Bear"?theme.red:s==="Bull"?theme.green:theme.accent,fontWeight:700,marginBottom:8}}>{s}</div>
                  <div style={{fontSize:11,color:theme.muted,lineHeight:1.6,marginBottom:12}}>{a}</div>
                  <div style={{fontSize:28,fontWeight:800,color:theme.fg}}>{fv}</div>
                  <div style={{fontSize:13,color:ud.startsWith("−")||ud.startsWith("-")?theme.red:theme.green}}>{ud}</div>
                </div>
              ))}
            </div>
            <div style={{background:"rgba(250,77,86,0.08)",border:"1px solid rgba(250,77,86,0.25)",borderRadius:10,padding:"12px 16px",marginBottom:16}}>
              <div style={{fontSize:12,fontWeight:700,color:theme.kill,marginBottom:4}}>BASE CASE CUT $164 → $140 ON 2026-08-20</div>
              <div style={{fontSize:13,lineHeight:1.6,color:theme.fg}}>The old base assumed 10%/yr EPS growth <em>and</em> a re-rate to 17×. The EPS growth survives — management guides low-double-digit for FY2028-30, driven by the buyback. The 17× re-rate does not survive HOKA decelerating to single digits and operating margin contracting. 14× is the defensible exit multiple; DECK traded as high as 17.7× FY2026 earnings within the last 52 weeks, so 14× is conservative rather than punitive.</div>
            </div>
            <div style={{background:theme.bg,borderRadius:10,padding:16}}>
              <div style={{fontSize:13,color:theme.muted,marginBottom:4}}>Fair Value Range</div>
              <div style={{fontSize:18,fontWeight:700,color:theme.fg}}>$66 – $195 · Base $140</div>
              <div style={{fontSize:12,color:theme.green,marginTop:4}}>Base case +58% from $88.56 · 3-year IRR 16.4%/yr vs 9.70% ORANGE hurdle · probability-weighted (25/55/20) about $132</div>
              <div style={{fontSize:12,color:theme.muted,marginTop:8}}>Not included in any scenario: up to $120M gross of IEEPA tariff refunds now being claimed, explicitly excluded from management guidance. Net realization will be materially below gross after manufacturer cost-sharing and tax.</div>
            </div>
          </div>
        )}
        {tab==="positionmgmt" && (
          <div style={{background:theme.card,border:`1px solid ${theme.border}`,borderRadius:14,padding:28}}>
            <h2 style={{fontSize:22,fontWeight:700,margin:"0 0 16px",color:theme.accent}}>Position Management {thesisMeta ? "" : "(cached — API unavailable)"}</h2>
            <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:28}}>
              {[[{label:"Add Zone",value:pos.add_zone || "at or below $105",detail:"Valuation entry"},{label:"Full Position",value:pos.full_position || "at or below $90",detail:"Staged, not gated"},{label:"Stop Loss",value:pos.stop_loss || "$72",detail:"Backstop; KCs are primary"},{label:"Trim Zone",value:pos.trim_zone || "$140 – $195",detail:"Base to bull"}]].map((ents: any) => ents.map((e: any) => (
                <div key={e.label} style={{background:theme.bg,border:`1px solid ${theme.border}`,borderRadius:10,padding:14,textAlign:"center"}}>
                  <div style={{fontSize:10,color:theme.muted,textTransform:"uppercase",marginBottom:4}}>{e.label}</div>
                  <div style={{fontSize:18,fontWeight:800,color:theme.fg}}>{e.value}</div>
                  <div style={{fontSize:11,color:theme.muted,marginTop:2}}>{e.detail}</div>
                </div>
              )))}
            </div>
            <div style={{fontSize:13,color:theme.muted,lineHeight:1.6}}>
              <p style={{margin:"0 0 10px"}}><strong style={{color:theme.fg}}>Current position: 2 shares at $94.78 cost basis, opened 2026-05-13 — about 1.7% of portfolio, down 6.6%.</strong> Target size is 5%.</p>
              <p style={{margin:"0 0 10px"}}>At $88.56 the price clears both the add zone and the full-position line. The prior version of this page gated the position to 3-4% because kill condition 1 made the October print a liquidation binary. <strong style={{color:theme.fg}}>That gate is removed</strong> — the rewritten condition 1 tests the HOKA/UGG crossover ratio, which cannot be tripped by one soft growth print. October is now a sizing decision, not a survival decision.</p>
              <p style={{margin:"0 0 10px"}}>Sizing is still staged rather than full, on the evidence rather than the rulebook: HOKA segment gross margin slipped 50bps, units fell 1.4%, and constant-currency growth was 4.8%. Build to roughly 3.4% now; take the balance to 5% only if the Q2 FY2027 print shows the crossover ratio still advancing and HOKA gross margin stabilizing.</p>
              <p style={{margin:0}}>Scale-out on the way up: one-third at $140, one-third at $165, balance to $195 or a kill condition. Written now, while there is no position pressure to ignore it.</p>
            </div>
          </div>
        )}
        {tab==="screener" && (
          <div style={{background:theme.card,border:`1px solid ${theme.border}`,borderRadius:14,padding:28}}>
            <h2 style={{fontSize:22,fontWeight:700,margin:"0 0 16px",color:theme.accent}}>Screener</h2>
            <p style={{fontSize:13,color:theme.muted,margin:"0 0 20px"}}>Clarion 6-component thesis health score, rescored 2026-08-20 against Q1 FY2027 results</p>
            <div style={{display:"flex",alignItems:"center",gap:16,marginBottom:24}}>
              <div style={{width:80,height:80,borderRadius:"50%",border:`4px solid ${theme.accent}`,display:"flex",alignItems:"center",justifyContent:"center",flexDirection:"column"}}>
                <div style={{fontSize:28,fontWeight:800,color:theme.fg}}>69</div>
                <div style={{fontSize:10,color:theme.muted}}>/ 100</div>
              </div>
              <div>
                <div style={{fontSize:16,fontWeight:700,color:theme.accent}}>HOLD — 72 → 67 → 69</div>
                <div style={{fontSize:12,color:theme.muted}}>55-74 = HOLD · 75+ = ADD · 40-54 = REDUCE · below 40 = EXIT</div>
              </div>
            </div>
            <div style={{display:"flex",flexDirection:"column",gap:10}}>
              {[["Valuation Safety (25%)","86",86],["Business Health (20%)","72",72],["Insider Alignment (10%)","50",50],["Catalyst Proximity (10%)","55",55],["Thesis Integrity (25%)","68",68],["Risk Environment (10%)","60",60]].map(([f,s,v]) => (
                <div key={f} style={{display:"flex",alignItems:"center",gap:12}}>
                  <div style={{width:180,fontSize:12,color:theme.muted,textAlign:"right"}}>{f}</div>
                  <div style={{flex:1,height:8,background:theme.bg,borderRadius:4,overflow:"hidden"}}>
                    <div style={{width:`${v}%`,height:"100%",background:v>=70?theme.green:v>=40?theme.yellow:theme.red,borderRadius:4}}/>
                  </div>
                  <div style={{width:60,fontSize:12,fontWeight:600,color:theme.fg}}>{s}</div>
                </div>
              ))}
            </div>
            <div style={{marginTop:20,fontSize:12,color:theme.muted,lineHeight:1.6}}>
              Two passes on 2026-08-20. First pass, on the 8-K headline: 72 → 67, with Thesis Integrity 80 → 62 and Business Health 85 → 68. Second pass, after reading Note 10 of the 10-Q: 67 → 69. Business Health 68 → 72 because segment operating income was flat rather than down and inventory fell; Thesis Integrity 62 → 68 because the crossover ratio — the actual thesis — advanced 139bps in the quarter. Neither the "margin-expanding compounder" claim nor the HOKA gross-margin slippage was rehabilitated; both remain marked against the score.
            </div>
          </div>
        )}
        {/* Footer */}
        <div style={{marginTop:32,padding:"14px 0",borderTop:`1px solid ${theme.border}`,display:"flex",justifyContent:"space-between",flexWrap:"wrap",gap:8,fontSize:11,color:theme.muted}}>
          <span>
            <a href="https://cis.zo.space" style={{color:theme.muted,textDecoration:"underline",textUnderlineOffset:3}}>cis.zo.space</a>
            {" · "}
            <a href="https://elendillabs.com" style={{color:theme.muted,textDecoration:"underline",textUnderlineOffset:3}}>elendillabs.com</a>
            {" · "}Jing Xie &amp; Oliver King — Managing Directors, Elendil Labs — Research only, not investment advice. Elendil Labs owns and operates the public research surfaces.
          </span>
          <span>Price data: yfinance — SEC: EDGAR CIK 0000910521 (8-K 0000910521-26-000015, 10-Q 0000910521-26-000022) — Price as of {priceAsOf}</span>
        </div>
      </div>
    </div>
  );
}