"""Typed model of a thesis document.

The on-disk format is markdown with a YAML metadata block (see
`docs/PRINCIPLES.md` Principle 2 and the thesis template generated by
`clarion-thesis-write`). This module defines the typed dataclasses
both skills (write + monitor) consume.

We intentionally don't model every prose section as a typed field —
parsing free-form prose creates round-trip headaches. The structured
parts (metadata, kill conditions, health components, history) are
typed; the rest stays as raw markdown.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from typing import Literal

Bucket = Literal["value", "systematic", "short", "yolo"]
Status = Literal["active", "watchlist", "closed", "killed"]
KillStatus = Literal["clear", "warning", "triggered"]
Action = Literal["EXIT", "REDUCE", "HOLD", "ADD"]

# Canonical health components — names match the template exactly. Order matters
# for rendering.
HEALTH_COMPONENT_NAMES: tuple[str, ...] = (
    "Valuation Safety",
    "Business Health",
    "Insider Alignment",
    "Catalyst Proximity",
    "Thesis Integrity",
    "Risk Environment",
)

# Default weights when a thesis is first scaffolded. Sums to 100.
DEFAULT_HEALTH_WEIGHTS: dict[str, int] = {
    "Valuation Safety": 25,
    "Business Health": 20,
    "Insider Alignment": 10,
    "Catalyst Proximity": 10,
    "Thesis Integrity": 25,
    "Risk Environment": 10,
}


@dataclass
class ThesisMetadata:
    """The YAML metadata block at the top of every thesis."""

    ticker: str
    company: str
    bucket: Bucket
    status: Status
    opened: date
    last_reviewed: date | None = None
    health_score: int | None = None    # 0-100; equal to body's Overall row
    cost_basis: float | None = None
    shares: int = 0
    portfolio_weight: float | None = None  # %


@dataclass
class HealthComponent:
    """One row of the Health Scoring table. Score is 0-100."""

    name: str
    weight: int       # %
    score: int        # 0-100
    notes: str = ""


@dataclass
class KillCondition:
    """One row of the Kill Conditions table."""

    description: str
    monitoring: str         # how to monitor (tool / data source)
    last_checked: date | None = None
    status: KillStatus = "clear"


@dataclass
class ValuationScenario:
    """One row of the Bear/Base/Bull valuation table."""

    label: Literal["bear", "base", "bull"]
    assumptions: str
    fair_value: float
    upside_pct: float       # signed; +25.0 = +25% upside


@dataclass
class HistoryEntry:
    """One row of the append-only History table."""

    date: date
    event: str              # OPENED, THESIS UPDATED, KILL TRIGGERED, ACTION CHANGED, etc.
    detail: str


@dataclass
class HealthSnapshot:
    """Result of a thesis-monitor health pass — scores plus a recommended action.

    `kill_triggered` overrides the score-derived action with EXIT.
    """

    components: list[HealthComponent]
    overall: int
    action: Action
    kill_triggered: bool = False
    kill_reasons: list[str] = field(default_factory=list)
    rationale: str = ""
